#menu1 = {'A': 5, 'B': 5, 'C': 5, 'D': 5, 'E': 5, 'X': 10}  # constant dict...using as a database...
menu1 = {'A': [5, 'Rose'], 'B': [5, 'Lily'], 'C': [5, 'Tulip'], 'D': [5, 'Daisy'], 'E': [5, 'Orchid']}
history = {}
